=== JustinXiong/DataTransfer/src/main/resources/TransferDefinitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.xtonic.com/TransferDefinitions" elementFormDefault="unqualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.xtonic.com/TransferDefinitions" attributeFormDefault="unqualified">
    <xsd:element name="transferDefinition" type="transferDefinitonType">
    </xsd:element>
    <xsd:complexType name="dataSourceType">
    	<xsd:sequence>
    		<xsd:element name="url" type="xsd:string" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="username" type="xsd:string" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="password" type="xsd:string" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="driverClass" type="xsd:string"
    			maxOccurs="1" minOccurs="1">
    		</xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="dbType" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>


    <xsd:complexType name="transferDefinitonType">
    	<xsd:sequence>
    		<xsd:element name="dataSources" type="dataSources"
    			maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="tables" type="tables" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="properties" type="properties"
    			maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="typehandlers" type="typehandlers"
    			maxOccurs="1" minOccurs="0">
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="dataSources">
    	<xsd:sequence maxOccurs="unbounded" minOccurs="1">
    		<xsd:element name="dataSource" type="dataSourceType"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="tables">
    	<xsd:sequence maxOccurs="unbounded" minOccurs="1">
    		<xsd:element name="table" type="tableType"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tableType">
    	<xsd:sequence>
    		<xsd:element name="srcs" type="srcs" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="changes" type="changes" maxOccurs="1"
    			minOccurs="0">
    		</xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="beanClass" type="xsd:string"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="targetDataSourceRef" type="xsd:string"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="table" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="taskImplClass" type="xsd:string"></xsd:attribute>
    </xsd:complexType>


    <xsd:complexType name="srcs">
    	<xsd:sequence>
            <xsd:element name="src" type="srcType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="srcType">
    	<xsd:attribute name="srcDataSourceRef" type="xsd:string"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="querySql" type="xsd:string"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="keyColumn" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="isMainSrc" type="xsd:string" use="optional"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="changeType">
    	<xsd:attribute name="columnName" type="xsd:string"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="targetType" type="xsd:string"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="srcType" type="xsd:string"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="handlerRef" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="changes">
    	<xsd:sequence>
    		<xsd:element name="change" type="changeType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="properties">
    	<xsd:sequence>
    		<xsd:element name="property" type="propertyType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="propertyType">
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="value" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="typehandlers">
    	<xsd:sequence>
    		<xsd:element name="typehandler" type="typehandler" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="typehandler">
    	<xsd:sequence></xsd:sequence>
    	<xsd:attribute name="handlerid" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="handlerClass" type="xsd:string"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== JustinXiong/DataTransfer/bak/TransferDefinitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:transferDefinition xmlns:p="http://www.xtonic.com/TransferDefinitions"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.xtonic.com/TransferDefinitions TransferDefinitions.xsd ">
	<dataSources>
		<dataSource id="targetDB" dbType="mysql">
			<url>jdbc:mysql://192.168.31.108:3306/test</url>
			<username>root</username>
			<password>jzh9866</password>
			<driverClass>com.mysql.jdbc.Driver</driverClass>
		</dataSource>
		<dataSource id="srcDB" dbType="mysql">
			<url>jdbc:mysql://192.168.31.108:3306/testA</url>
			<username>root</username>
			<password>jzh9866</password>
			<driverClass>com.mysql.jdbc.Driver</driverClass>
		</dataSource>
	</dataSources>
	<tables>
		<!-- <table beanClass="com.xtonic.entity.User" table="user"  
			targetDataSourceRef="targetDB" id="hello">
			<srcs>
			"SELECT ID,USERNAME,AGE,INTERSTED,MEMO FROM SRCUSER"
			SELECT id, name as username, nianl as age,aihao as intersted,beizhu as memo FROM testA.src2Table
				<src querySql="select a.id,a.name as username,a.age,b.intersted,b.memo from testA.src3User a left join testA.src4User b on a.id = b.id"
					srcDataSourceRef="srcDB" keyColumn="id" />
			</srcs>
			<changes>
				<change columnName="age" targetType="java.lang.Integer" srcType="java.lang.String"   handlerRef="StringToInteger"/>
			</changes>
		</table> -->
	  	<table beanClass="com.xtonic.entity.User" table="user"  
			targetDataSourceRef="targetDB" id="userTable"  taskImplClass="com.xtonic.task.impl.MoreSrcsTransferTask">
			<srcs>
				<src querySql="select id,name as username,age from src3User "
					srcDataSourceRef="srcDB" keyColumn="id"  isMainSrc="true"/>
					<src querySql="select id,inttrested as intersted from src5user"
					srcDataSourceRef="targetDB" keyColumn="id" />
			</srcs>
			<changes>
				<change columnName="age" targetType="java.lang.Integer" srcType="java.lang.String"   handlerRef="StringToInteger"/>
			</changes>
		</table> 
		<!--  <table beanClass="com.xtonic.entity.User" table="user"  
			targetDataSourceRef="targetDB" id="hello"  taskImplClass="com.xtonic.task.impl.InsertTask">
			<srcs>
				<src querySql="SELECT ID,USERNAME,AGE,INTERSTED,MEMO FROM SRCUSER"
					srcDataSourceRef="srcDB" keyColumn="id"  />
			</srcs>
		</table>  -->
	<!-- 	 <table beanClass="com.xtonic.entity.Test_Table_1" table="TEST_TABLE_1"  
			targetDataSourceRef="targetDB" id="hello" >
			<srcs>
				<src querySql="SELECT id,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16 FROM TEST_TABLE_1"
					srcDataSourceRef="srcDB" keyColumn="id"  />
			</srcs>
		</table>  -->
		
		<!-- <table beanClass="com.xtonic.entity.Test_Table_2" table="TEST_TABLE_2"  
			targetDataSourceRef="targetDB" id="hello1" >
			<srcs>
				<src querySql="SELECT id,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15  FROM TEST_TABLE_2"
					srcDataSourceRef="srcDB" keyColumn="id"  />
			</srcs>
		</table> -->
		<!--
		<table beanClass="com.xtonic.entity.Test_Table_3" table="TEST_TABLE_3"  
			targetDataSourceRef="targetDB" id="hello2" >
			<srcs>
				<src querySql="SELECT id,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16 FROM TEST_TABLE_3"
					srcDataSourceRef="srcDB" keyColumn="id"  />
			</srcs>
		</table>
		<table beanClass="com.xtonic.entity.Test_Table_4" table="TEST_TABLE_4"  
			targetDataSourceRef="targetDB" id="hello3" >
			<srcs>
				<src querySql="SELECT id,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16 FROM TEST_TABLE_4"
					srcDataSourceRef="srcDB" keyColumn="id"  />
			</srcs>
		</table>
		<table beanClass="com.xtonic.entity.Test_Table_5" table="TEST_TABLE_5"  
			targetDataSourceRef="targetDB" id="hello4" >
			<srcs>
				<src querySql="SELECT id,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16 FROM TEST_TABLE_5"
					srcDataSourceRef="srcDB" keyColumn="id"  />
			</srcs>
		</table>
		<table beanClass="com.xtonic.entity.Test_Table_6" table="TEST_TABLE_6"  
			targetDataSourceRef="targetDB" id="hello5" >
			<srcs>
				<src querySql="SELECT id,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15,c16 FROM TEST_TABLE_6"
					srcDataSourceRef="srcDB" keyColumn="id"  />
			</srcs>
		</table> -->
	</tables>
	<properties>
		<property name="poolSize" value="2"></property>
		<property name="pageSize" value="10000"></property>
		<property name="commitSize" value="5000"></property>
		<property name="fialRecordFilePath"  value="/home/neil/MyStudio/Workspace/DateTransfer/src/main/resources/logs/" ></property> 
	</properties>
	<typehandlers>
		<typehandler handlerid="StringToInteger" handlerClass="com.xtonic.type.impl.StringToIntegerHandler" />
	</typehandlers>
</p:transferDefinition>
